#!/usr/bin/env bash

function usage() {
    echo "usage:" $0 "<command> [<options>]"
    echo
    echo "Available commands:"
    echo "    import    Import data from an existing Munin setup to InfluxDB and (optionally) generate a Grafana dashboard"
    echo "    fetch     Update values in InfluxDB based on the previous import"
    echo "    help      Print this message"
}

function launch_install_cron() {
    python -m munininfluxdb.fetch --install-cron "python -m munininfluxdb.fetch"
}

if [[ $1 == "import" ]]; then
    shift
    sudo su - munin bash -c "python -m munininfluxdb.import $@" && launch_install_cron
elif [[ $1 == "fetch" ]]; then
    if [[ $2 == "--install-cron" ]]; then
        launch_install_cron
    else
        shift
        sudo su - munin bash -c "python -m munininfluxdb.fetch $@"
    fi
elif [[ $1 == "help" ]]; then
    usage
    exit 0
else
    usage
    exit 1
fi

